# Generated by Django 6.0.5 on 2026-05-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentGlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tts_voice', models.CharField(choices=[('es-US-Neural2-A', 'Mujer — Natural (es-US-Neural2-A)'), ('es-US-Neural2-C', 'Mujer — Formal (es-US-Neural2-C)'), ('es-US-Neural2-B', 'Hombre — Natural (es-US-Neural2-B)'), ('es-US-Neural2-D', 'Hombre — Formal (es-US-Neural2-D)')], default='es-US-Neural2-A', max_length=50)),
                ('tts_speed', models.FloatField(default=1.0)),
                ('tts_pitch', models.FloatField(default=0.0)),
                ('llm_temperature', models.FloatField(default=0.5)),
                ('llm_max_tokens', models.IntegerField(default=300)),
                ('vad_silence_ms', models.IntegerField(default=900)),
                ('max_call_duration_seconds', models.IntegerField(default=600)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración global del agente',
            },
        ),
        migrations.AddField(
            model_name='script',
            name='llm_max_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='llm_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='max_call_duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='tts_pitch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='tts_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='tts_voice',
            field=models.CharField(blank=True, choices=[('es-US-Neural2-A', 'Mujer — Natural (es-US-Neural2-A)'), ('es-US-Neural2-C', 'Mujer — Formal (es-US-Neural2-C)'), ('es-US-Neural2-B', 'Hombre — Natural (es-US-Neural2-B)'), ('es-US-Neural2-D', 'Hombre — Formal (es-US-Neural2-D)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='vad_silence_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
