# Generated by Django 6.0.5 on 2026-05-11 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftp_path', models.CharField(max_length=1000, unique=True, verbose_name='Ruta FTP')),
                ('audio_file', models.FileField(blank=True, upload_to='audio/', verbose_name='Archivo de audio')),
                ('call_date', models.DateField(blank=True, null=True, verbose_name='Fecha de llamada')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Duración (s)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('transcribing', 'Transcribiendo'), ('analyzing', 'Analizando'), ('done', 'Completada'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='campaigns.agent')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Llamada',
                'verbose_name_plural': 'Llamadas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_items', models.JSONField(default=list, verbose_name='Ítems del script')),
                ('summary', models.TextField(verbose_name='Resumen')),
                ('score', models.IntegerField(verbose_name='Puntaje')),
                ('llm_model', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='calls.call')),
            ],
            options={
                'verbose_name': 'Análisis de cumplimiento',
                'verbose_name_plural': 'Análisis de cumplimiento',
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(verbose_name='Transcripción')),
                ('assemblyai_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='calls.call')),
            ],
            options={
                'verbose_name': 'Transcripción',
                'verbose_name_plural': 'Transcripciones',
            },
        ),
    ]
