# Generated by Django 6.0.5 on 2026-05-12 21:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch', '0001_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('calling', 'Calling'), ('analyzing', 'Analyzing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('audio_gcs_url', models.CharField(blank=True, default='', max_length=500)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('bot_call_id', models.CharField(blank=True, default='', max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='batch.batchcallitem')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True, default='')),
                ('compliance_score', models.IntegerField(blank=True, null=True)),
                ('llm_model', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='calls.call')),
            ],
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['status'], name='calls_call_status_03473e_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['campaign', '-created_at'], name='calls_call_campaig_7218fe_idx'),
        ),
    ]
