# Generated by Django 6.0.5 on 2026-05-12 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('csv', 'CSV upload'), ('api', 'REST API')], max_length=10)),
                ('total_calls', models.IntegerField(default=0)),
                ('done_calls', models.IntegerField(default=0)),
                ('failed_calls', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_jobs', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchCallItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('input_params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('calling', 'Calling'), ('done', 'Done'), ('failed', 'Failed'), ('retry', 'Retry')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('batch_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='batch.batchjob')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['batch_job', 'status'], name='batch_batch_batch_j_16d26f_idx')],
            },
        ),
    ]
